-- MySQL Script generated by MySQL Workbench
-- Thu Sep 29 11:15:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Portfolio` DEFAULT CHARACTER SET utf8 ;
USE `Portfolio` ;

-- -----------------------------------------------------
-- Table `Portfolio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`persona` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fechaNac` DATE NULL,
  `URL_githyb` VARCHAR(100) NULL,
  `correo` VARCHAR(45) NULL,
  `url_foto` VARCHAR(100) NULL,
  `URL_linkTelegram` VARCHAR(100) NOT NULL,
  `URL_linkWhatsapp` VARCHAR(100) NOT NULL,
  `URL_fotolinkSobreMI` VARCHAR(100) NOT NULL,
  `URL_fotolinkEstudios` VARCHAR(100) NOT NULL,
  `URL_fotolinkExperiencia` VARCHAR(100) NOT NULL,
  `URL_fotolinkSkills` VARCHAR(100) NOT NULL,
  `URL_fotolinkProyectos` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`experiencia` (
  `idexperiencia` INT NOT NULL,
  `empresa` VARCHAR(45) NOT NULL,
  `esTrabajoActual` TINYINT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  `descripcion` VARCHAR(200) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`idexperiencia`),
  INDEX `fk_experiencia_persona_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `Portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`Usuario` (
  `id_usuario` INT NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Usuario_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `Portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`estudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`estudios` (
  `idestudios` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `institucion` VARCHAR(45) NULL,
  `año` DATE NULL,
  `persona_id` INT NOT NULL,
  `URL_fotolink_estudios` VARCHAR(100) NULL,
  PRIMARY KEY (`idestudios`),
  INDEX `fk_estudios_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudios_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `Portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`skills` (
  `idskills` INT NOT NULL,
  `nombre_skill` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(100) NOT NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`idskills`),
  INDEX `fk_skills_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_skills_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `Portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`proyectos` (
  `idproyectos` INT NOT NULL,
  `nombreProyecto` VARCHAR(45) NULL,
  `url_proyecto` VARCHAR(100) NULL,
  `url_foto_proyecto` VARCHAR(100) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`idproyectos`),
  INDEX `fk_proyectos_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `Portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Portfolio`.`sobre_mi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`sobre_mi` (
  `idsobre_mi` INT NOT NULL,
  `URL_video_sobreMi` VARCHAR(100) NULL,
  `texto_presentacion` VARCHAR(300) NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`idsobre_mi`),
  INDEX `fk_sobre_mi_persona1_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_sobre_mi_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `Portfolio`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
